name: Build and Test with Mamba

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: environment.yaml
        init-shell: >-
          bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Install dependencies
      run: |
        micromamba run -n mattersim uv pip install -e .

    - name: Install test dependencies
      run: |
        micromamba run -n mattersim uv pip install -e ".[dev]"

    - name: Build extension
      run: |
        micromamba run -n mattersim python setup.py build_ext --inplace

    - name: Run tests
      run: |
        micromamba run -n mattersim pytest -s tests
